services:
  #Node Container
  node:
    image: node:lts
    container_name: reactjs-todolist-node
    tty: true
    user: "node:node"
    working_dir: /var/www
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    environment:
      HOST: 0.0.0.0

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local